import { AllocationPage } from "@/components/AllocationPage";
import type { SourceStock } from "@/lib/allocate";
import stocksData from "@/data/stocks.json";

// src/data/stocks.json is generated by scripts/generate-stock-data.js
// (via `npm run generate:data`) and gitignored - it won't exist until
// that's been run at least once with a real FINNHUB_API_KEY. Cast
// rather than rely on inferred JSON-module typing, since the shape is
// a contract with the generation script, not something to re-derive
// from whatever happens to be on disk at typecheck time.
const { generatedAt, stocks } = stocksData as { generatedAt: string; stocks: SourceStock[] };

function App() {
  return <AllocationPage stocks={stocks} generatedAt={generatedAt} />;
}

export default App;
